import { Inter } from "next/font/google";
import "./globals.css";
import TopNavigation from "@/components/TopNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full flex-col">
          <TopNavigation />
          {children}
        </div>
      </body>
    </html>
  );
}
